global:
  scrape_interval: 10s
  scrape_timeout: 2s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'web:3000'
          - 'prometheus:9090'
          # - 'idonotexists:564'
